name: Run Cypress Tests - Solve Zapamtilica

on:
  workflow_dispatch:  # This makes the workflow manually triggered

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Install Cypress directly
    - name: Install Cypress
      run: npm install cypress --save-dev

    # Run Cypress tests
    - name: Run Cypress Tests
      run: npx cypress run --spec 'cypress/solveTheGame.cy.js'
